==89998== Memcheck, a memory error detector
==89998== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==89998== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==89998== Command: /home/marija/Desktop/2024_Analysis_12-Uno/valgrind/memcheck/../../12-UNO/UNO/build/run_tests
==89998== Parent PID: 89528
==89998== 
==89998== Conditional jump or move depends on uninitialised value(s)
==89998==    at 0x13D826: Catch::RunContext::handleExpr(Catch::AssertionInfo const&, Catch::ITransientExpression const&, Catch::AssertionReaction&) (catch.hpp:13049)
==89998==    by 0x12C627: Catch::AssertionHandler::handleExpr(Catch::ITransientExpression const&) (catch.hpp:8230)
==89998==    by 0x202AAB: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:72)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==  Uninitialised value was created by a heap allocation
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x20299D: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:69)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== Conditional jump or move depends on uninitialised value(s)
==89998==    at 0x13D826: Catch::RunContext::handleExpr(Catch::AssertionInfo const&, Catch::ITransientExpression const&, Catch::AssertionReaction&) (catch.hpp:13049)
==89998==    by 0x12C627: Catch::AssertionHandler::handleExpr(Catch::ITransientExpression const&) (catch.hpp:8230)
==89998==    by 0x203368: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:128)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==  Uninitialised value was created by a heap allocation
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x235E7E: Pile::lastCard() const (pile.cpp:31)
==89998==    by 0x20313B: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:123)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 
==89998== HEAP SUMMARY:
==89998==     in use at exit: 2,453,578 bytes in 24,371 blocks
==89998==   total heap usage: 326,029 allocs, 301,658 frees, 33,963,114 bytes allocated
==89998== 
==89998== 16 bytes in 1 blocks are still reachable in loss record 490 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x5D23C4F: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5CA44ED: QThread::currentThread() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5B9019E: QCoreApplicationPrivate::QCoreApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x522B858: QGuiApplicationPrivate::QGuiApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x5237C2D: QGuiApplication::QGuiApplication(int&, char**, int) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x157332: main (main.cpp:7)
==89998== 
==89998== 20 bytes in 1 blocks are indirectly lost in loss record 1,619 of 7,505
==89998==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x5CBB860: QArrayData::allocate(QArrayData**, long long, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5C89D2E: QString::QString(long long, Qt::Initialization) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5C9E3A9: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5C84613: QString::fromUtf8(QByteArrayView) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x1FDC5D: QString::operator=(char const*) (qstring.h:1035)
==89998==    by 0x1FC08C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:159)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998== 
==89998== 24 bytes in 1 blocks are indirectly lost in loss record 2,206 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x2024F2: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:37)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 24 bytes in 1 blocks are indirectly lost in loss record 2,207 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x2069BA: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:66)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 24 bytes in 1 blocks are indirectly lost in loss record 2,208 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x2069E0: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:67)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 24 bytes in 1 blocks are indirectly lost in loss record 2,209 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x206A01: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:68)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 24 bytes in 1 blocks are indirectly lost in loss record 2,210 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x2089D9: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:323)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 24 bytes in 1 blocks are indirectly lost in loss record 2,211 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x2089FF: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:324)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 24 bytes in 1 blocks are indirectly lost in loss record 2,212 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x208A25: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:325)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 24 bytes in 1 blocks are indirectly lost in loss record 2,213 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x20CC7B: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:19)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 24 bytes in 1 blocks are definitely lost in loss record 2,214 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x235E7E: Pile::lastCard() const (pile.cpp:31)
==89998==    by 0x20313B: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:123)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 24 bytes in 1 blocks are definitely lost in loss record 2,215 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x2040DC: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:224)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 24 bytes in 1 blocks are definitely lost in loss record 2,216 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x20629C: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:14)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 24 bytes in 1 blocks are definitely lost in loss record 2,217 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x206994: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:65)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 24 bytes in 1 blocks are definitely lost in loss record 2,218 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x209688: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:422)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 24 bytes in 1 blocks are definitely lost in loss record 2,219 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x20D487: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:80)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 32 bytes in 1 blocks are indirectly lost in loss record 3,517 of 7,505
==89998==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x5CBB860: QArrayData::allocate(QArrayData**, long long, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5C89D2E: QString::QString(long long, Qt::Initialization) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5C9E3A9: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5C84613: QString::fromUtf8(QByteArrayView) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x1FDC5D: QString::operator=(char const*) (qstring.h:1035)
==89998==    by 0x1FC059: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:156)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998== 
==89998== 34 bytes in 1 blocks are indirectly lost in loss record 3,531 of 7,505
==89998==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x5CBB860: QArrayData::allocate(QArrayData**, long long, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x20193E: QTypedArrayData<Card*>::allocate(long long, QArrayData::AllocationOption) (qarraydata.h:105)
==89998==    by 0x23314C: QArrayDataPointer<Card*>::allocateGrow(QArrayDataPointer<Card*> const&, long long, QArrayData::GrowthPosition) (qarraydatapointer.h:352)
==89998==    by 0x23280E: QArrayDataPointer<Card*>::reallocateAndGrow(QArrayData::GrowthPosition, long long, QArrayDataPointer<Card*>*) (qarraydatapointer.h:213)
==89998==    by 0x232B1A: QArrayDataPointer<Card*>::detachAndGrow(QArrayData::GrowthPosition, long long, Card* const**, QArrayDataPointer<Card*>*) (qarraydatapointer.h:194)
==89998==    by 0x232208: void QtPrivate::QPodArrayOps<Card*>::emplace<Card*&>(long long, Card*&) (qarraydataops.h:174)
==89998==    by 0x231707: Card*& QList<Card*>::emplaceBack<Card*&>(Card*&) (qlist.h:856)
==89998==    by 0x230E12: QList<Card*>::append(Card*) (qlist.h:433)
==89998==    by 0x230A08: QList<Card*>::push_back(Card*) (qlist.h:651)
==89998==    by 0x235E09: Pile::pushCard(Card*) (pile.cpp:17)
==89998==    by 0x20CCB5: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:20)
==89998== 
==89998== 48 bytes in 1 blocks are still reachable in loss record 3,903 of 7,505
==89998==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x6BD5B09: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==89998==    by 0x6BCE3A9: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==89998==    by 0x6BCFBC7: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==89998==    by 0x6BCFCF6: g_source_attach (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==89998==    by 0xBA7D69A: ??? (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.0)
==89998==    by 0xBA7D847: ??? (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.0)
==89998==    by 0x6C04531: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==89998==    by 0x6BFED91: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==89998==    by 0x6587AA3: start_thread (pthread_create.c:447)
==89998==    by 0x6614A63: clone (clone.S:100)
==89998== 
==89998== 56 bytes in 1 blocks are still reachable in loss record 4,468 of 7,505
==89998==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x6BD5B09: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==89998==    by 0xB046F96: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32)
==89998==    by 0xB050B02: gtk_entry_set_icon_from_pixbuf (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32)
==89998==    by 0xB04559A: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32)
==89998==    by 0xBBBC6C3: g_object_run_dispose (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.0)
==89998==    by 0xAEBCE7C: ??? (in /home/marija/Qt/6.5.3/gcc_64/plugins/platformthemes/libqgtk3.so)
==89998==    by 0xAEB31C4: ??? (in /home/marija/Qt/6.5.3/gcc_64/plugins/platformthemes/libqgtk3.so)
==89998==    by 0xAEBBF24: ??? (in /home/marija/Qt/6.5.3/gcc_64/plugins/platformthemes/libqgtk3.so)
==89998==    by 0x522B0C6: QGuiApplicationPrivate::~QGuiApplicationPrivate() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x522B518: QGuiApplicationPrivate::~QGuiApplicationPrivate() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x157380: main (main.cpp:7)
==89998== 
==89998== 56 bytes in 1 blocks are still reachable in loss record 4,470 of 7,505
==89998==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x6BD5B09: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==89998==    by 0xB046F96: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32)
==89998==    by 0xB050B02: gtk_entry_set_icon_from_pixbuf (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32)
==89998==    by 0xB0455B5: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32)
==89998==    by 0xBBBC6C3: g_object_run_dispose (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.0)
==89998==    by 0xAEBCE7C: ??? (in /home/marija/Qt/6.5.3/gcc_64/plugins/platformthemes/libqgtk3.so)
==89998==    by 0xAEB31C4: ??? (in /home/marija/Qt/6.5.3/gcc_64/plugins/platformthemes/libqgtk3.so)
==89998==    by 0xAEBBF24: ??? (in /home/marija/Qt/6.5.3/gcc_64/plugins/platformthemes/libqgtk3.so)
==89998==    by 0x522B0C6: QGuiApplicationPrivate::~QGuiApplicationPrivate() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x522B518: QGuiApplicationPrivate::~QGuiApplicationPrivate() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x157380: main (main.cpp:7)
==89998== 
==89998== 66 bytes in 1 blocks are still reachable in loss record 4,778 of 7,505
==89998==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x5CBB860: QArrayData::allocate(QArrayData**, long long, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5BECDE1: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5D2BDD7: QThreadStorageData::get() const (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x54857A9: QFontCache::cleanup() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x522B03F: QGuiApplicationPrivate::~QGuiApplicationPrivate() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x522B518: QGuiApplicationPrivate::~QGuiApplicationPrivate() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x157380: main (main.cpp:7)
==89998== 
==89998== 66 bytes in 1 blocks are indirectly lost in loss record 4,780 of 7,505
==89998==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x5CBB860: QArrayData::allocate(QArrayData**, long long, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x20193E: QTypedArrayData<Card*>::allocate(long long, QArrayData::AllocationOption) (qarraydata.h:105)
==89998==    by 0x23314C: QArrayDataPointer<Card*>::allocateGrow(QArrayDataPointer<Card*> const&, long long, QArrayData::GrowthPosition) (qarraydatapointer.h:352)
==89998==    by 0x23280E: QArrayDataPointer<Card*>::reallocateAndGrow(QArrayData::GrowthPosition, long long, QArrayDataPointer<Card*>*) (qarraydatapointer.h:213)
==89998==    by 0x232B1A: QArrayDataPointer<Card*>::detachAndGrow(QArrayData::GrowthPosition, long long, Card* const**, QArrayDataPointer<Card*>*) (qarraydatapointer.h:194)
==89998==    by 0x2370EF: QtPrivate::QCommonArrayOps<Card*>::growAppend(Card* const*, Card* const*) (qarraydataops.h:922)
==89998==    by 0x236F07: QList<Card*>::append(QList<Card*>::const_iterator, QList<Card*>::const_iterator) (qlist.h:804)
==89998==    by 0x236D6A: QList<Card*>::append(QList<Card*> const&) (qlist.h:445)
==89998==    by 0x2369EE: Player::setHand(QList<Card*> const&) (player.cpp:110)
==89998==    by 0x206AA9: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:72)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998== 
==89998== 66 bytes in 1 blocks are indirectly lost in loss record 4,781 of 7,505
==89998==    at 0x484DB80: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x5CBB920: QArrayData::reallocateUnaligned(QArrayData*, void*, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x23358A: QTypedArrayData<Card*>::reallocateUnaligned(QTypedArrayData<Card*>*, Card**, long long, QArrayData::AllocationOption) (qarraydata.h:117)
==89998==    by 0x232F8C: QtPrivate::QPodArrayOps<Card*>::reallocate(long long, QArrayData::AllocationOption) (qarraydataops.h:259)
==89998==    by 0x2327F2: QArrayDataPointer<Card*>::reallocateAndGrow(QArrayData::GrowthPosition, long long, QArrayDataPointer<Card*>*) (qarraydatapointer.h:208)
==89998==    by 0x232B1A: QArrayDataPointer<Card*>::detachAndGrow(QArrayData::GrowthPosition, long long, Card* const**, QArrayDataPointer<Card*>*) (qarraydatapointer.h:194)
==89998==    by 0x232208: void QtPrivate::QPodArrayOps<Card*>::emplace<Card*&>(long long, Card*&) (qarraydataops.h:174)
==89998==    by 0x231707: Card*& QList<Card*>::emplaceBack<Card*&>(Card*&) (qlist.h:856)
==89998==    by 0x230E12: QList<Card*>::append(Card*) (qlist.h:433)
==89998==    by 0x230A08: QList<Card*>::push_back(Card*) (qlist.h:651)
==89998==    by 0x235E09: Pile::pushCard(Card*) (pile.cpp:17)
==89998==    by 0x208A8C: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:328)
==89998== 
==89998== 90 (32 direct, 58 indirect) bytes in 1 blocks are definitely lost in loss record 5,557 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x20CC34: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:17)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 96 bytes in 1 blocks are still reachable in loss record 5,589 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x5D2C994: QWaitCondition::QWaitCondition() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5CA50A3: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5D23C5D: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5CA44ED: QThread::currentThread() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5B9019E: QCoreApplicationPrivate::QCoreApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x522B858: QGuiApplicationPrivate::QGuiApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x5237C2D: QGuiApplication::QGuiApplication(int&, char**, int) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x157332: main (main.cpp:7)
==89998== 
==89998== 96 bytes in 4 blocks are definitely lost in loss record 6,420 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FF48: Deck::Deck() (deck.cpp:41)
==89998==    by 0x1FBD15: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:135)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 96 bytes in 4 blocks are definitely lost in loss record 6,421 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FF7C: Deck::Deck() (deck.cpp:42)
==89998==    by 0x1FBD15: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:135)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 96 bytes in 4 blocks are definitely lost in loss record 6,422 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FF48: Deck::Deck() (deck.cpp:41)
==89998==    by 0x1FC76C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:206)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 96 bytes in 4 blocks are definitely lost in loss record 6,423 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FF7C: Deck::Deck() (deck.cpp:42)
==89998==    by 0x1FC76C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:206)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 96 bytes in 4 blocks are definitely lost in loss record 6,424 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FF48: Deck::Deck() (deck.cpp:41)
==89998==    by 0x1FC9B7: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:222)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 96 bytes in 4 blocks are definitely lost in loss record 6,425 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FF7C: Deck::Deck() (deck.cpp:42)
==89998==    by 0x1FC9B7: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:222)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 96 bytes in 4 blocks are definitely lost in loss record 6,426 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FF48: Deck::Deck() (deck.cpp:41)
==89998==    by 0x20CCFB: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:24)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 96 bytes in 4 blocks are definitely lost in loss record 6,427 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FF7C: Deck::Deck() (deck.cpp:42)
==89998==    by 0x20CCFB: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:24)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 96 bytes in 4 blocks are definitely lost in loss record 6,428 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FF48: Deck::Deck() (deck.cpp:41)
==89998==    by 0x20D46F: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:78)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 96 bytes in 4 blocks are definitely lost in loss record 6,429 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FF7C: Deck::Deck() (deck.cpp:42)
==89998==    by 0x20D46F: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:78)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 108 (56 direct, 52 indirect) bytes in 1 blocks are definitely lost in loss record 6,533 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x1FBFF6: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:155)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 152 bytes in 1 blocks are still reachable in loss record 6,790 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x5D23C01: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5CA44ED: QThread::currentThread() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5B9019E: QCoreApplicationPrivate::QCoreApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x522B858: QGuiApplicationPrivate::QGuiApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x5237C2D: QGuiApplication::QGuiApplication(int&, char**, int) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x157332: main (main.cpp:7)
==89998== 
==89998== 170 (32 direct, 138 indirect) bytes in 1 blocks are definitely lost in loss record 6,849 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x2089BD: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:321)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 200 bytes in 1 blocks are still reachable in loss record 6,918 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x5CA5047: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5D23C5D: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5CA44ED: QThread::currentThread() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x5B9019E: QCoreApplicationPrivate::QCoreApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x522B858: QGuiApplicationPrivate::QGuiApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x5237C2D: QGuiApplication::QGuiApplication(int&, char**, int) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==89998==    by 0x157332: main (main.cpp:7)
==89998== 
==89998== 250 (112 direct, 138 indirect) bytes in 1 blocks are definitely lost in loss record 6,988 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x206978: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:64)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== 288 bytes in 12 blocks are definitely lost in loss record 7,050 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FEAB: Deck::Deck() (deck.cpp:33)
==89998==    by 0x1FBD15: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:135)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 288 bytes in 12 blocks are definitely lost in loss record 7,051 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FEE7: Deck::Deck() (deck.cpp:34)
==89998==    by 0x1FBD15: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:135)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 288 bytes in 12 blocks are definitely lost in loss record 7,052 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FEAB: Deck::Deck() (deck.cpp:33)
==89998==    by 0x1FC76C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:206)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 288 bytes in 12 blocks are definitely lost in loss record 7,053 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FEE7: Deck::Deck() (deck.cpp:34)
==89998==    by 0x1FC76C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:206)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 288 bytes in 12 blocks are definitely lost in loss record 7,054 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FEAB: Deck::Deck() (deck.cpp:33)
==89998==    by 0x1FC9B7: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:222)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 288 bytes in 12 blocks are definitely lost in loss record 7,055 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FEE7: Deck::Deck() (deck.cpp:34)
==89998==    by 0x1FC9B7: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:222)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 288 bytes in 12 blocks are definitely lost in loss record 7,056 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FEAB: Deck::Deck() (deck.cpp:33)
==89998==    by 0x20CCFB: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:24)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 288 bytes in 12 blocks are definitely lost in loss record 7,057 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FEE7: Deck::Deck() (deck.cpp:34)
==89998==    by 0x20CCFB: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:24)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 288 bytes in 12 blocks are definitely lost in loss record 7,058 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FEAB: Deck::Deck() (deck.cpp:33)
==89998==    by 0x20D46F: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:78)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 288 bytes in 12 blocks are definitely lost in loss record 7,059 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FEE7: Deck::Deck() (deck.cpp:34)
==89998==    by 0x20D46F: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:78)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 864 bytes in 36 blocks are definitely lost in loss record 7,285 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FDE7: Deck::Deck() (deck.cpp:26)
==89998==    by 0x1FBD15: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:135)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 864 bytes in 36 blocks are definitely lost in loss record 7,286 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FDE7: Deck::Deck() (deck.cpp:26)
==89998==    by 0x1FC76C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:206)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 864 bytes in 36 blocks are definitely lost in loss record 7,287 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FDE7: Deck::Deck() (deck.cpp:26)
==89998==    by 0x1FC9B7: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:222)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 864 bytes in 36 blocks are definitely lost in loss record 7,288 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FDE7: Deck::Deck() (deck.cpp:26)
==89998==    by 0x20CCFB: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:24)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 864 bytes in 36 blocks are definitely lost in loss record 7,289 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FDE7: Deck::Deck() (deck.cpp:26)
==89998==    by 0x20D46F: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:78)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 936 bytes in 39 blocks are definitely lost in loss record 7,296 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FE25: Deck::Deck() (deck.cpp:27)
==89998==    by 0x20D46F: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:78)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 960 bytes in 40 blocks are definitely lost in loss record 7,301 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FE25: Deck::Deck() (deck.cpp:27)
==89998==    by 0x1FBD15: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:135)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 960 bytes in 40 blocks are definitely lost in loss record 7,302 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FE25: Deck::Deck() (deck.cpp:27)
==89998==    by 0x1FC76C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:206)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 960 bytes in 40 blocks are definitely lost in loss record 7,303 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FE25: Deck::Deck() (deck.cpp:27)
==89998==    by 0x1FC9B7: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:222)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 960 bytes in 40 blocks are definitely lost in loss record 7,304 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x22FE25: Deck::Deck() (deck.cpp:27)
==89998==    by 0x20CCFB: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:24)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998== 
==89998== 1,026 bytes in 1 blocks are indirectly lost in loss record 7,324 of 7,505
==89998==    at 0x484DB80: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x5CBB920: QArrayData::reallocateUnaligned(QArrayData*, void*, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==89998==    by 0x23358A: QTypedArrayData<Card*>::reallocateUnaligned(QTypedArrayData<Card*>*, Card**, long long, QArrayData::AllocationOption) (qarraydata.h:117)
==89998==    by 0x232F8C: QtPrivate::QPodArrayOps<Card*>::reallocate(long long, QArrayData::AllocationOption) (qarraydataops.h:259)
==89998==    by 0x2327F2: QArrayDataPointer<Card*>::reallocateAndGrow(QArrayData::GrowthPosition, long long, QArrayDataPointer<Card*>*) (qarraydatapointer.h:208)
==89998==    by 0x232B1A: QArrayDataPointer<Card*>::detachAndGrow(QArrayData::GrowthPosition, long long, Card* const**, QArrayDataPointer<Card*>*) (qarraydatapointer.h:194)
==89998==    by 0x232208: void QtPrivate::QPodArrayOps<Card*>::emplace<Card*&>(long long, Card*&) (qarraydataops.h:174)
==89998==    by 0x231707: Card*& QList<Card*>::emplaceBack<Card*&>(Card*&) (qlist.h:856)
==89998==    by 0x230E12: QList<Card*>::append(Card*) (qlist.h:433)
==89998==    by 0x230A08: QList<Card*>::push_back(Card*) (qlist.h:651)
==89998==    by 0x235E09: Pile::pushCard(Card*) (pile.cpp:17)
==89998==    by 0x202530: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:41)
==89998== 
==89998== 1,082 (32 direct, 1,050 indirect) bytes in 1 blocks are definitely lost in loss record 7,336 of 7,505
==89998==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==89998==    by 0x2024D6: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:36)
==89998==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==89998==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==89998==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==89998==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==89998==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==89998==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==89998==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==89998==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==89998==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==89998==    by 0x15735F: main (main.cpp:8)
==89998== 
==89998== LEAK SUMMARY:
==89998==    definitely lost: 13,344 bytes in 550 blocks
==89998==    indirectly lost: 1,436 bytes in 14 blocks
==89998==      possibly lost: 0 bytes in 0 blocks
==89998==    still reachable: 690 bytes in 8 blocks
==89998==                       of which reachable via heuristic:
==89998==                         newarray           : 760 bytes in 5 blocks
==89998==         suppressed: 2,334,212 bytes in 22,869 blocks
==89998== 
==89998== For lists of detected and suppressed errors, rerun with: -s
==89998== ERROR SUMMARY: 43 errors from 43 contexts (suppressed: 55 from 55)
