==95503== Memcheck, a memory error detector
==95503== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==95503== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==95503== Command: /home/marija/Desktop/2024_Analysis_12-Uno/valgrind/memcheck/../../12-UNO/UNO/build/run_tests
==95503== Parent PID: 94999
==95503== 
==95503== Invalid read of size 8
==95503==    at 0x235DA0: Pile::~Pile() (pile.cpp:9)
==95503==    by 0x20263B: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:45)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503==  Address 0xf843ad0 is 0 bytes inside a block of size 24 free'd
==95503==    at 0x484A61D: operator delete(void*, unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22EFF6: Card::~Card() (card.cpp:67)
==95503==    by 0x235DAE: Pile::~Pile() (pile.cpp:9)
==95503==    by 0x20263B: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:45)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==  Block was alloc'd at
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2024F2: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:37)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== Invalid write of size 8
==95503==    at 0x22EFC3: Card::~Card() (card.cpp:67)
==95503==    by 0x22EFE5: Card::~Card() (card.cpp:67)
==95503==    by 0x235DAE: Pile::~Pile() (pile.cpp:9)
==95503==    by 0x20263B: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:45)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==  Address 0xf843ad0 is 0 bytes inside a block of size 24 free'd
==95503==    at 0x484A61D: operator delete(void*, unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22EFF6: Card::~Card() (card.cpp:67)
==95503==    by 0x235DAE: Pile::~Pile() (pile.cpp:9)
==95503==    by 0x20263B: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:45)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==  Block was alloc'd at
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2024F2: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:37)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== Invalid free() / delete / delete[] / realloc()
==95503==    at 0x484A61D: operator delete(void*, unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22EFF6: Card::~Card() (card.cpp:67)
==95503==    by 0x235DAE: Pile::~Pile() (pile.cpp:9)
==95503==    by 0x20263B: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:45)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==  Address 0xf843ad0 is 0 bytes inside a block of size 24 free'd
==95503==    at 0x484A61D: operator delete(void*, unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22EFF6: Card::~Card() (card.cpp:67)
==95503==    by 0x235DAE: Pile::~Pile() (pile.cpp:9)
==95503==    by 0x20263B: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:45)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==  Block was alloc'd at
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2024F2: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:37)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== Conditional jump or move depends on uninitialised value(s)
==95503==    at 0x13D826: Catch::RunContext::handleExpr(Catch::AssertionInfo const&, Catch::ITransientExpression const&, Catch::AssertionReaction&) (catch.hpp:13049)
==95503==    by 0x12C627: Catch::AssertionHandler::handleExpr(Catch::ITransientExpression const&) (catch.hpp:8230)
==95503==    by 0x202ACC: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:73)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==  Uninitialised value was created by a heap allocation
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2029BE: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:70)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== Conditional jump or move depends on uninitialised value(s)
==95503==    at 0x629AA7D: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33)
==95503==    by 0x62AB3C1: std::ostream& std::ostream::_M_insert<long>(long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33)
==95503==    by 0x1FA85B: Catch::ReusableStringStream& Catch::ReusableStringStream::operator<< <Card::CARD_TYPE>(Card::CARD_TYPE const&) (catch.hpp:1451)
==95503==    by 0x1FA79D: std::enable_if<Catch::Detail::IsStreamInsertable<Card::CARD_TYPE>::value, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::type Catch::StringMaker<Card::CARD_TYPE, void>::convert<Card::CARD_TYPE>(Card::CARD_TYPE const&) (catch.hpp:1623)
==95503==    by 0x1FA69E: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > Catch::Detail::stringify<Card::CARD_TYPE>(Card::CARD_TYPE const&) (catch.hpp:1645)
==95503==    by 0x1FA539: Catch::BinaryExpr<Card::CARD_TYPE const&, Card::CARD_TYPE const&>::streamReconstructedExpression(std::ostream&) const (catch.hpp:2231)
==95503==    by 0x12C3E9: Catch::(anonymous namespace)::operator<<(std::ostream&, Catch::ITransientExpression const&) (catch.hpp:8189)
==95503==    by 0x12C527: Catch::operator<<(std::ostream&, Catch::LazyExpression const&) (catch.hpp:8212)
==95503==    by 0x1713AA: Catch::ReusableStringStream& Catch::ReusableStringStream::operator<< <Catch::LazyExpression>(Catch::LazyExpression const&) (catch.hpp:1451)
==95503==    by 0x12CAFA: Catch::AssertionResultData::reconstructExpression[abi:cxx11]() const (catch.hpp:8301)
==95503==    by 0x12D02C: Catch::AssertionResult::getExpandedExpression[abi:cxx11]() const (catch.hpp:8367)
==95503==    by 0x12CF4B: Catch::AssertionResult::hasExpandedExpression() const (catch.hpp:8363)
==95503==  Uninitialised value was created by a heap allocation
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2029BE: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:70)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== Use of uninitialised value of size 8
==95503==    at 0x629A95B: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33)
==95503==    by 0x629AAA7: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33)
==95503==    by 0x62AB3C1: std::ostream& std::ostream::_M_insert<long>(long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33)
==95503==    by 0x1FA85B: Catch::ReusableStringStream& Catch::ReusableStringStream::operator<< <Card::CARD_TYPE>(Card::CARD_TYPE const&) (catch.hpp:1451)
==95503==    by 0x1FA79D: std::enable_if<Catch::Detail::IsStreamInsertable<Card::CARD_TYPE>::value, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::type Catch::StringMaker<Card::CARD_TYPE, void>::convert<Card::CARD_TYPE>(Card::CARD_TYPE const&) (catch.hpp:1623)
==95503==    by 0x1FA69E: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > Catch::Detail::stringify<Card::CARD_TYPE>(Card::CARD_TYPE const&) (catch.hpp:1645)
==95503==    by 0x1FA539: Catch::BinaryExpr<Card::CARD_TYPE const&, Card::CARD_TYPE const&>::streamReconstructedExpression(std::ostream&) const (catch.hpp:2231)
==95503==    by 0x12C3E9: Catch::(anonymous namespace)::operator<<(std::ostream&, Catch::ITransientExpression const&) (catch.hpp:8189)
==95503==    by 0x12C527: Catch::operator<<(std::ostream&, Catch::LazyExpression const&) (catch.hpp:8212)
==95503==    by 0x1713AA: Catch::ReusableStringStream& Catch::ReusableStringStream::operator<< <Catch::LazyExpression>(Catch::LazyExpression const&) (catch.hpp:1451)
==95503==    by 0x12CAFA: Catch::AssertionResultData::reconstructExpression[abi:cxx11]() const (catch.hpp:8301)
==95503==    by 0x12D02C: Catch::AssertionResult::getExpandedExpression[abi:cxx11]() const (catch.hpp:8367)
==95503==  Uninitialised value was created by a heap allocation
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2029BE: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:70)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== Conditional jump or move depends on uninitialised value(s)
==95503==    at 0x629A96D: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33)
==95503==    by 0x629AAA7: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33)
==95503==    by 0x62AB3C1: std::ostream& std::ostream::_M_insert<long>(long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33)
==95503==    by 0x1FA85B: Catch::ReusableStringStream& Catch::ReusableStringStream::operator<< <Card::CARD_TYPE>(Card::CARD_TYPE const&) (catch.hpp:1451)
==95503==    by 0x1FA79D: std::enable_if<Catch::Detail::IsStreamInsertable<Card::CARD_TYPE>::value, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::type Catch::StringMaker<Card::CARD_TYPE, void>::convert<Card::CARD_TYPE>(Card::CARD_TYPE const&) (catch.hpp:1623)
==95503==    by 0x1FA69E: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > Catch::Detail::stringify<Card::CARD_TYPE>(Card::CARD_TYPE const&) (catch.hpp:1645)
==95503==    by 0x1FA539: Catch::BinaryExpr<Card::CARD_TYPE const&, Card::CARD_TYPE const&>::streamReconstructedExpression(std::ostream&) const (catch.hpp:2231)
==95503==    by 0x12C3E9: Catch::(anonymous namespace)::operator<<(std::ostream&, Catch::ITransientExpression const&) (catch.hpp:8189)
==95503==    by 0x12C527: Catch::operator<<(std::ostream&, Catch::LazyExpression const&) (catch.hpp:8212)
==95503==    by 0x1713AA: Catch::ReusableStringStream& Catch::ReusableStringStream::operator<< <Catch::LazyExpression>(Catch::LazyExpression const&) (catch.hpp:1451)
==95503==    by 0x12CAFA: Catch::AssertionResultData::reconstructExpression[abi:cxx11]() const (catch.hpp:8301)
==95503==    by 0x12D02C: Catch::AssertionResult::getExpandedExpression[abi:cxx11]() const (catch.hpp:8367)
==95503==  Uninitialised value was created by a heap allocation
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2029BE: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:70)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== Conditional jump or move depends on uninitialised value(s)
==95503==    at 0x629AADC: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33)
==95503==    by 0x62AB3C1: std::ostream& std::ostream::_M_insert<long>(long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.33)
==95503==    by 0x1FA85B: Catch::ReusableStringStream& Catch::ReusableStringStream::operator<< <Card::CARD_TYPE>(Card::CARD_TYPE const&) (catch.hpp:1451)
==95503==    by 0x1FA79D: std::enable_if<Catch::Detail::IsStreamInsertable<Card::CARD_TYPE>::value, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::type Catch::StringMaker<Card::CARD_TYPE, void>::convert<Card::CARD_TYPE>(Card::CARD_TYPE const&) (catch.hpp:1623)
==95503==    by 0x1FA69E: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > Catch::Detail::stringify<Card::CARD_TYPE>(Card::CARD_TYPE const&) (catch.hpp:1645)
==95503==    by 0x1FA539: Catch::BinaryExpr<Card::CARD_TYPE const&, Card::CARD_TYPE const&>::streamReconstructedExpression(std::ostream&) const (catch.hpp:2231)
==95503==    by 0x12C3E9: Catch::(anonymous namespace)::operator<<(std::ostream&, Catch::ITransientExpression const&) (catch.hpp:8189)
==95503==    by 0x12C527: Catch::operator<<(std::ostream&, Catch::LazyExpression const&) (catch.hpp:8212)
==95503==    by 0x1713AA: Catch::ReusableStringStream& Catch::ReusableStringStream::operator<< <Catch::LazyExpression>(Catch::LazyExpression const&) (catch.hpp:1451)
==95503==    by 0x12CAFA: Catch::AssertionResultData::reconstructExpression[abi:cxx11]() const (catch.hpp:8301)
==95503==    by 0x12D02C: Catch::AssertionResult::getExpandedExpression[abi:cxx11]() const (catch.hpp:8367)
==95503==    by 0x12CF4B: Catch::AssertionResult::hasExpandedExpression() const (catch.hpp:8363)
==95503==  Uninitialised value was created by a heap allocation
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2029BE: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:70)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== Conditional jump or move depends on uninitialised value(s)
==95503==    at 0x13D826: Catch::RunContext::handleExpr(Catch::AssertionInfo const&, Catch::ITransientExpression const&, Catch::AssertionReaction&) (catch.hpp:13049)
==95503==    by 0x12C627: Catch::AssertionHandler::handleExpr(Catch::ITransientExpression const&) (catch.hpp:8230)
==95503==    by 0x203389: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:129)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==  Uninitialised value was created by a heap allocation
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x235E9E: Pile::lastCard() const (pile.cpp:31)
==95503==    by 0x20315C: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:124)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 
==95503== HEAP SUMMARY:
==95503==     in use at exit: 2,452,536 bytes in 24,369 blocks
==95503==   total heap usage: 326,045 allocs, 301,783 frees, 33,964,350 bytes allocated
==95503== 
==95503== 8 bytes in 1 blocks are still reachable in loss record 152 of 7,503
==95503==    at 0x484DB80: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x6BD6859: g_realloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0xBBD077C: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.0)
==95503==    by 0xBBD44BF: g_type_interface_add_prerequisite (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.0)
==95503==    by 0xBA5BE30: g_proxy_resolver_get_type (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.0)
==95503==    by 0xBA4CAEC: ??? (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.0)
==95503==    by 0xBA4D608: ??? (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.0)
==95503==    by 0xBABDD19: g_settings_backend_get_default (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.0)
==95503==    by 0xBABEEEE: ??? (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.0)
==95503==    by 0xBBBEBB9: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.0)
==95503==    by 0xBBC0BC2: g_object_new_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.0)
==95503==    by 0xBBC0F4E: g_object_new (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.0)
==95503== 
==95503== 16 bytes in 1 blocks are still reachable in loss record 490 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x5D23C4F: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5CA44ED: QThread::currentThread() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5B9019E: QCoreApplicationPrivate::QCoreApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x522B858: QGuiApplicationPrivate::QGuiApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x5237C2D: QGuiApplication::QGuiApplication(int&, char**, int) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x157332: main (main.cpp:7)
==95503== 
==95503== 20 bytes in 1 blocks are indirectly lost in loss record 1,619 of 7,503
==95503==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x5CBB860: QArrayData::allocate(QArrayData**, long long, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5C89D2E: QString::QString(long long, Qt::Initialization) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5C9E3A9: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5C84613: QString::fromUtf8(QByteArrayView) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x1FDC5D: QString::operator=(char const*) (qstring.h:1035)
==95503==    by 0x1FC08C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:159)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503== 
==95503== 24 bytes in 1 blocks are indirectly lost in loss record 2,206 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2069DA: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:66)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 24 bytes in 1 blocks are indirectly lost in loss record 2,207 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x206A00: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:67)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 24 bytes in 1 blocks are indirectly lost in loss record 2,208 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x206A21: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:68)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 24 bytes in 1 blocks are indirectly lost in loss record 2,209 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2089F9: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:323)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 24 bytes in 1 blocks are indirectly lost in loss record 2,210 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x208A1F: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:324)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 24 bytes in 1 blocks are indirectly lost in loss record 2,211 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x208A45: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:325)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 24 bytes in 1 blocks are indirectly lost in loss record 2,212 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x20CC9B: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:19)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 24 bytes in 1 blocks are definitely lost in loss record 2,213 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2029BE: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:70)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 24 bytes in 1 blocks are definitely lost in loss record 2,214 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x235E9E: Pile::lastCard() const (pile.cpp:31)
==95503==    by 0x20315C: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:124)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 24 bytes in 1 blocks are definitely lost in loss record 2,215 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2040FD: C_A_T_C_H_T_E_S_T_0() (test_pile.cpp:225)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 24 bytes in 1 blocks are definitely lost in loss record 2,216 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2062BC: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:14)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 24 bytes in 1 blocks are definitely lost in loss record 2,217 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2069B4: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:65)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 24 bytes in 1 blocks are definitely lost in loss record 2,218 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2096A8: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:422)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 24 bytes in 1 blocks are definitely lost in loss record 2,219 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x20D4A7: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:80)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 32 bytes in 1 blocks are indirectly lost in loss record 3,517 of 7,503
==95503==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x5CBB860: QArrayData::allocate(QArrayData**, long long, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5C89D2E: QString::QString(long long, Qt::Initialization) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5C9E3A9: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5C84613: QString::fromUtf8(QByteArrayView) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x1FDC5D: QString::operator=(char const*) (qstring.h:1035)
==95503==    by 0x1FC059: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:156)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503== 
==95503== 34 bytes in 1 blocks are indirectly lost in loss record 3,531 of 7,503
==95503==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x5CBB860: QArrayData::allocate(QArrayData**, long long, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x20193E: QTypedArrayData<Card*>::allocate(long long, QArrayData::AllocationOption) (qarraydata.h:105)
==95503==    by 0x23316C: QArrayDataPointer<Card*>::allocateGrow(QArrayDataPointer<Card*> const&, long long, QArrayData::GrowthPosition) (qarraydatapointer.h:352)
==95503==    by 0x23282E: QArrayDataPointer<Card*>::reallocateAndGrow(QArrayData::GrowthPosition, long long, QArrayDataPointer<Card*>*) (qarraydatapointer.h:213)
==95503==    by 0x232B3A: QArrayDataPointer<Card*>::detachAndGrow(QArrayData::GrowthPosition, long long, Card* const**, QArrayDataPointer<Card*>*) (qarraydatapointer.h:194)
==95503==    by 0x232228: void QtPrivate::QPodArrayOps<Card*>::emplace<Card*&>(long long, Card*&) (qarraydataops.h:174)
==95503==    by 0x231727: Card*& QList<Card*>::emplaceBack<Card*&>(Card*&) (qlist.h:856)
==95503==    by 0x230E32: QList<Card*>::append(Card*) (qlist.h:433)
==95503==    by 0x230A28: QList<Card*>::push_back(Card*) (qlist.h:651)
==95503==    by 0x235E29: Pile::pushCard(Card*) (pile.cpp:17)
==95503==    by 0x20CCD5: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:20)
==95503== 
==95503== 48 bytes in 1 blocks are still reachable in loss record 3,907 of 7,503
==95503==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x6BD5B09: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0x6BCE3A9: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0x6BCFBC7: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0x6BCFCF6: g_source_attach (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0xBA7D69A: ??? (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.0)
==95503==    by 0xBA7D847: ??? (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.0)
==95503==    by 0x6C04531: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0x6BFED91: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0x6587AA3: start_thread (pthread_create.c:447)
==95503==    by 0x6614A63: clone (clone.S:100)
==95503== 
==95503== 56 bytes in 1 blocks are still reachable in loss record 4,332 of 7,503
==95503==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x6C2ABC1: g_rw_lock_reader_lock (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0x6BDD527: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0x6BDD6AF: g_log_writer_default (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0x6BD5053: g_log_structured_array (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0x6BD53DB: g_log_default_handler (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0x6BD567F: g_logv (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0x6BD5962: g_log (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0xBA4D4CC: ??? (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.0)
==95503==    by 0xBABDD19: g_settings_backend_get_default (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.0)
==95503==    by 0xBABEEEE: ??? (in /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.0)
==95503==    by 0xBBBEBB9: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.0)
==95503== 
==95503== 56 bytes in 1 blocks are still reachable in loss record 4,468 of 7,503
==95503==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x6BD5B09: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0xB046F96: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32)
==95503==    by 0xB050B02: gtk_entry_set_icon_from_pixbuf (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32)
==95503==    by 0xB04559A: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32)
==95503==    by 0xBBBC6C3: g_object_run_dispose (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.0)
==95503==    by 0xAEBCE7C: ??? (in /home/marija/Qt/6.5.3/gcc_64/plugins/platformthemes/libqgtk3.so)
==95503==    by 0xAEB31C4: ??? (in /home/marija/Qt/6.5.3/gcc_64/plugins/platformthemes/libqgtk3.so)
==95503==    by 0xAEBBF24: ??? (in /home/marija/Qt/6.5.3/gcc_64/plugins/platformthemes/libqgtk3.so)
==95503==    by 0x522B0C6: QGuiApplicationPrivate::~QGuiApplicationPrivate() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x522B518: QGuiApplicationPrivate::~QGuiApplicationPrivate() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x157380: main (main.cpp:7)
==95503== 
==95503== 56 bytes in 1 blocks are still reachable in loss record 4,470 of 7,503
==95503==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x6BD5B09: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.0)
==95503==    by 0xB046F96: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32)
==95503==    by 0xB050B02: gtk_entry_set_icon_from_pixbuf (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32)
==95503==    by 0xB0455B5: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32)
==95503==    by 0xBBBC6C3: g_object_run_dispose (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.0)
==95503==    by 0xAEBCE7C: ??? (in /home/marija/Qt/6.5.3/gcc_64/plugins/platformthemes/libqgtk3.so)
==95503==    by 0xAEB31C4: ??? (in /home/marija/Qt/6.5.3/gcc_64/plugins/platformthemes/libqgtk3.so)
==95503==    by 0xAEBBF24: ??? (in /home/marija/Qt/6.5.3/gcc_64/plugins/platformthemes/libqgtk3.so)
==95503==    by 0x522B0C6: QGuiApplicationPrivate::~QGuiApplicationPrivate() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x522B518: QGuiApplicationPrivate::~QGuiApplicationPrivate() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x157380: main (main.cpp:7)
==95503== 
==95503== 66 bytes in 1 blocks are still reachable in loss record 4,778 of 7,503
==95503==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x5CBB860: QArrayData::allocate(QArrayData**, long long, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5BECDE1: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5D2BDD7: QThreadStorageData::get() const (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x54857A9: QFontCache::cleanup() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x522B03F: QGuiApplicationPrivate::~QGuiApplicationPrivate() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x522B518: QGuiApplicationPrivate::~QGuiApplicationPrivate() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x157380: main (main.cpp:7)
==95503== 
==95503== 66 bytes in 1 blocks are indirectly lost in loss record 4,780 of 7,503
==95503==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x5CBB860: QArrayData::allocate(QArrayData**, long long, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x20193E: QTypedArrayData<Card*>::allocate(long long, QArrayData::AllocationOption) (qarraydata.h:105)
==95503==    by 0x23316C: QArrayDataPointer<Card*>::allocateGrow(QArrayDataPointer<Card*> const&, long long, QArrayData::GrowthPosition) (qarraydatapointer.h:352)
==95503==    by 0x23282E: QArrayDataPointer<Card*>::reallocateAndGrow(QArrayData::GrowthPosition, long long, QArrayDataPointer<Card*>*) (qarraydatapointer.h:213)
==95503==    by 0x232B3A: QArrayDataPointer<Card*>::detachAndGrow(QArrayData::GrowthPosition, long long, Card* const**, QArrayDataPointer<Card*>*) (qarraydatapointer.h:194)
==95503==    by 0x23710F: QtPrivate::QCommonArrayOps<Card*>::growAppend(Card* const*, Card* const*) (qarraydataops.h:922)
==95503==    by 0x236F27: QList<Card*>::append(QList<Card*>::const_iterator, QList<Card*>::const_iterator) (qlist.h:804)
==95503==    by 0x236D8A: QList<Card*>::append(QList<Card*> const&) (qlist.h:445)
==95503==    by 0x236A0E: Player::setHand(QList<Card*> const&) (player.cpp:110)
==95503==    by 0x206AC9: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:72)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503== 
==95503== 66 bytes in 1 blocks are indirectly lost in loss record 4,781 of 7,503
==95503==    at 0x484DB80: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x5CBB920: QArrayData::reallocateUnaligned(QArrayData*, void*, long long, long long, QArrayData::AllocationOption) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x2335AA: QTypedArrayData<Card*>::reallocateUnaligned(QTypedArrayData<Card*>*, Card**, long long, QArrayData::AllocationOption) (qarraydata.h:117)
==95503==    by 0x232FAC: QtPrivate::QPodArrayOps<Card*>::reallocate(long long, QArrayData::AllocationOption) (qarraydataops.h:259)
==95503==    by 0x232812: QArrayDataPointer<Card*>::reallocateAndGrow(QArrayData::GrowthPosition, long long, QArrayDataPointer<Card*>*) (qarraydatapointer.h:208)
==95503==    by 0x232B3A: QArrayDataPointer<Card*>::detachAndGrow(QArrayData::GrowthPosition, long long, Card* const**, QArrayDataPointer<Card*>*) (qarraydatapointer.h:194)
==95503==    by 0x232228: void QtPrivate::QPodArrayOps<Card*>::emplace<Card*&>(long long, Card*&) (qarraydataops.h:174)
==95503==    by 0x231727: Card*& QList<Card*>::emplaceBack<Card*&>(Card*&) (qlist.h:856)
==95503==    by 0x230E32: QList<Card*>::append(Card*) (qlist.h:433)
==95503==    by 0x230A28: QList<Card*>::push_back(Card*) (qlist.h:651)
==95503==    by 0x235E29: Pile::pushCard(Card*) (pile.cpp:17)
==95503==    by 0x208AAC: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:328)
==95503== 
==95503== 90 (32 direct, 58 indirect) bytes in 1 blocks are definitely lost in loss record 5,557 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x20CC54: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:17)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 96 bytes in 1 blocks are still reachable in loss record 5,589 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x5D2C994: QWaitCondition::QWaitCondition() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5CA50A3: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5D23C5D: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5CA44ED: QThread::currentThread() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5B9019E: QCoreApplicationPrivate::QCoreApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x522B858: QGuiApplicationPrivate::QGuiApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x5237C2D: QGuiApplication::QGuiApplication(int&, char**, int) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x157332: main (main.cpp:7)
==95503== 
==95503== 96 bytes in 4 blocks are definitely lost in loss record 6,420 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF68: Deck::Deck() (deck.cpp:41)
==95503==    by 0x1FBD15: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:135)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 96 bytes in 4 blocks are definitely lost in loss record 6,421 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF9C: Deck::Deck() (deck.cpp:42)
==95503==    by 0x1FBD15: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:135)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 96 bytes in 4 blocks are definitely lost in loss record 6,422 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF68: Deck::Deck() (deck.cpp:41)
==95503==    by 0x1FC76C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:206)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 96 bytes in 4 blocks are definitely lost in loss record 6,423 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF9C: Deck::Deck() (deck.cpp:42)
==95503==    by 0x1FC76C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:206)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 96 bytes in 4 blocks are definitely lost in loss record 6,424 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF68: Deck::Deck() (deck.cpp:41)
==95503==    by 0x1FC9B7: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:222)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 96 bytes in 4 blocks are definitely lost in loss record 6,425 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF9C: Deck::Deck() (deck.cpp:42)
==95503==    by 0x1FC9B7: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:222)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 96 bytes in 4 blocks are definitely lost in loss record 6,426 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF68: Deck::Deck() (deck.cpp:41)
==95503==    by 0x20CD1B: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:24)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 96 bytes in 4 blocks are definitely lost in loss record 6,427 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF9C: Deck::Deck() (deck.cpp:42)
==95503==    by 0x20CD1B: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:24)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 96 bytes in 4 blocks are definitely lost in loss record 6,428 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF68: Deck::Deck() (deck.cpp:41)
==95503==    by 0x20D48F: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:78)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 96 bytes in 4 blocks are definitely lost in loss record 6,429 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF9C: Deck::Deck() (deck.cpp:42)
==95503==    by 0x20D48F: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:78)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 108 (56 direct, 52 indirect) bytes in 1 blocks are definitely lost in loss record 6,533 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x1FBFF6: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:155)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 152 bytes in 1 blocks are still reachable in loss record 6,790 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x5D23C01: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5CA44ED: QThread::currentThread() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5B9019E: QCoreApplicationPrivate::QCoreApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x522B858: QGuiApplicationPrivate::QGuiApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x5237C2D: QGuiApplication::QGuiApplication(int&, char**, int) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x157332: main (main.cpp:7)
==95503== 
==95503== 170 (32 direct, 138 indirect) bytes in 1 blocks are definitely lost in loss record 6,849 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x2089DD: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:321)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 200 bytes in 1 blocks are still reachable in loss record 6,918 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x5CA5047: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5D23C5D: ??? (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5CA44ED: QThread::currentThread() (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x5B9019E: QCoreApplicationPrivate::QCoreApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3)
==95503==    by 0x522B858: QGuiApplicationPrivate::QGuiApplicationPrivate(int&, char**) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x5237C2D: QGuiApplication::QGuiApplication(int&, char**, int) (in /home/marija/Qt/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3)
==95503==    by 0x157332: main (main.cpp:7)
==95503== 
==95503== 250 (112 direct, 138 indirect) bytes in 1 blocks are definitely lost in loss record 6,988 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x206998: C_A_T_C_H_T_E_S_T_0() (test_player.cpp:64)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503==    by 0x15735F: main (main.cpp:8)
==95503== 
==95503== 288 bytes in 12 blocks are definitely lost in loss record 7,050 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FECB: Deck::Deck() (deck.cpp:33)
==95503==    by 0x1FBD15: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:135)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 288 bytes in 12 blocks are definitely lost in loss record 7,051 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF07: Deck::Deck() (deck.cpp:34)
==95503==    by 0x1FBD15: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:135)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 288 bytes in 12 blocks are definitely lost in loss record 7,052 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FECB: Deck::Deck() (deck.cpp:33)
==95503==    by 0x1FC76C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:206)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 288 bytes in 12 blocks are definitely lost in loss record 7,053 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF07: Deck::Deck() (deck.cpp:34)
==95503==    by 0x1FC76C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:206)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 288 bytes in 12 blocks are definitely lost in loss record 7,054 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FECB: Deck::Deck() (deck.cpp:33)
==95503==    by 0x1FC9B7: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:222)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 288 bytes in 12 blocks are definitely lost in loss record 7,055 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF07: Deck::Deck() (deck.cpp:34)
==95503==    by 0x1FC9B7: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:222)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 288 bytes in 12 blocks are definitely lost in loss record 7,056 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FECB: Deck::Deck() (deck.cpp:33)
==95503==    by 0x20CD1B: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:24)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 288 bytes in 12 blocks are definitely lost in loss record 7,057 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF07: Deck::Deck() (deck.cpp:34)
==95503==    by 0x20CD1B: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:24)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 288 bytes in 12 blocks are definitely lost in loss record 7,058 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FECB: Deck::Deck() (deck.cpp:33)
==95503==    by 0x20D48F: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:78)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 288 bytes in 12 blocks are definitely lost in loss record 7,059 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FF07: Deck::Deck() (deck.cpp:34)
==95503==    by 0x20D48F: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:78)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 864 bytes in 36 blocks are definitely lost in loss record 7,285 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FE07: Deck::Deck() (deck.cpp:26)
==95503==    by 0x1FBD15: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:135)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 864 bytes in 36 blocks are definitely lost in loss record 7,286 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FE07: Deck::Deck() (deck.cpp:26)
==95503==    by 0x1FC76C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:206)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 864 bytes in 36 blocks are definitely lost in loss record 7,287 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FE07: Deck::Deck() (deck.cpp:26)
==95503==    by 0x1FC9B7: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:222)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 864 bytes in 36 blocks are definitely lost in loss record 7,288 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FE07: Deck::Deck() (deck.cpp:26)
==95503==    by 0x20CD1B: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:24)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 864 bytes in 36 blocks are definitely lost in loss record 7,289 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FE07: Deck::Deck() (deck.cpp:26)
==95503==    by 0x20D48F: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:78)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 936 bytes in 39 blocks are definitely lost in loss record 7,296 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FE45: Deck::Deck() (deck.cpp:27)
==95503==    by 0x20D48F: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:78)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 960 bytes in 40 blocks are definitely lost in loss record 7,301 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FE45: Deck::Deck() (deck.cpp:27)
==95503==    by 0x1FBD15: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:135)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 960 bytes in 40 blocks are definitely lost in loss record 7,302 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FE45: Deck::Deck() (deck.cpp:27)
==95503==    by 0x1FC76C: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:206)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 960 bytes in 40 blocks are definitely lost in loss record 7,303 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FE45: Deck::Deck() (deck.cpp:27)
==95503==    by 0x1FC9B7: C_A_T_C_H_T_E_S_T_0() (test_deck.cpp:222)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== 960 bytes in 40 blocks are definitely lost in loss record 7,304 of 7,503
==95503==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95503==    by 0x22FE45: Deck::Deck() (deck.cpp:27)
==95503==    by 0x20CD1B: C_A_T_C_H_T_E_S_T_0() (test_game.cpp:24)
==95503==    by 0x14415D: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==95503==    by 0x143394: Catch::TestCase::invoke() const (catch.hpp:14169)
==95503==    by 0x13D69F: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==95503==    by 0x13D3C4: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==95503==    by 0x13BE50: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==95503==    by 0x13F045: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==95503==    by 0x1404AC: Catch::Session::runInternal() (catch.hpp:13562)
==95503==    by 0x140186: Catch::Session::run() (catch.hpp:13518)
==95503==    by 0x1812EE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==95503== 
==95503== LEAK SUMMARY:
==95503==    definitely lost: 13,336 bytes in 550 blocks
==95503==    indirectly lost: 386 bytes in 12 blocks
==95503==      possibly lost: 0 bytes in 0 blocks
==95503==    still reachable: 754 bytes in 10 blocks
==95503==                       of which reachable via heuristic:
==95503==                         newarray           : 760 bytes in 5 blocks
==95503==         suppressed: 2,334,164 bytes in 22,867 blocks
==95503== 
==95503== For lists of detected and suppressed errors, rerun with: -s
==95503== ERROR SUMMARY: 368 errors from 50 contexts (suppressed: 55 from 55)
